# Generated by Django 3.0.3 on 2020-05-16 21:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('solicitante', models.CharField(max_length=30)),
                ('endereco_origem', models.CharField(max_length=50)),
                ('contato_origem', models.CharField(max_length=30)),
                ('servico', models.TextField()),
                ('endereco_destino', models.CharField(max_length=30)),
                ('contato_destino', models.CharField(max_length=30)),
                ('observacoes', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_id', to='solicitacao.Empresa')),
            ],
            options={
                'verbose_name_plural': 'Solicitações',
            },
        ),
    ]
