# Generated by Django 2.1.2 on 2018-10-19 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('solicitante', models.CharField(max_length=30)),
                ('endereco_origem', models.CharField(max_length=50)),
                ('contato_origem', models.CharField(max_length=30)),
                ('servico', models.TextField()),
                ('endereco_destino', models.CharField(max_length=30)),
                ('contato_destino', models.CharField(max_length=30)),
                ('observacoes', models.TextField()),
                ('empresa', models.ForeignKey(on_delete='CASCADE', to='solicitacao.Empresa')),
            ],
        ),
    ]
