# Generated by Django 2.1.2 on 2018-10-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='empresa',
            field=models.ForeignKey(on_delete='CASCADE', related_name='empresa_id', to='solicitacao.Empresa'),
        ),
    ]
