# Generated by Django 2.1.2 on 2018-10-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_auto_20181016_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='data',
            field=models.DateField(),
        ),
    ]
