# Generated by Django 2.1.2 on 2018-10-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_auto_20181019_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
