# Generated by Django 2.1.2 on 2018-10-18 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0003_auto_20181016_2306'),
        ('solicitacao', '0002_auto_20181017_1737'),
    ]

    operations = [
    ]
