# Generated by Django 2.1.2 on 2018-10-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0004_empresa_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='data',
        ),
    ]
