# Generated by Django 2.1.7 on 2019-04-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0005_remove_empresa_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'verbose_name_plural': 'Solicitações'},
        ),
    ]
