# Generated by Django 2.1.2 on 2018-10-24 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0005_remove_empresa_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
