# Generated by Django 2.1.2 on 2018-11-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0006_empresa_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitacao',
            new_name='Solicitacao_refactor',
        ),
        migrations.AlterModelOptions(
            name='solicitacao_refactor',
            options={'verbose_name_plural': 'Solicitações'},
        ),
    ]
