# Generated by Django 2.1.2 on 2018-11-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0007_auto_20181114_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitacao_refactor',
            new_name='Solicitacao',
        ),
    ]
